config/routes.rb
Cbtg::Application.routes.draw do

  resources :tipodocs

  resources :formapgtos

  resources :cxdiarios

  resources :cofres

  resources :vddesserts

  resources :ctrldesserts

  resources :desserts

  resources :cards

  resources :rodizios

  resources :units

  resources :unidades

  resources :pagamentos

  resources :movimentos

  resources :falta

  root :to => redirect("/funcionarios")

  resources :categories

  resources :ocorrencia

  resources :cargos

  resources :funcionarios

  resources :vales

  resources :fornecedors

  resources :produtos

  resources :agendas

  resources :comandos

  resources :sites

  resources :rts

  resources :ctgs

  resources :mtgs

  resources :socios

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :rodizios
end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/category.rb
 class Category < ActiveRecord::Base
  alias_attribute :name, :descricao
  has_many :produtos
end

app/models/cofre.rb
class Cofre < ActiveRecord::Base
end

app/models/comando.rb
class Comando < ActiveRecord::Base
end

app/models/cxdiario.rb
class Cxdiario < ActiveRecord::Base
end

app/models/dessert.rb
class Dessert < ActiveRecord::Base
  has_many :ctrldesserts
end

app/models/faltum.rb
class Faltum < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/formapgto.rb
class Formapgto < ActiveRecord::Base
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  alias_attribute :name, :nome
  has_many :pagamentos
end

app/models/movimento.rb
class Movimento < ActiveRecord::Base
  belongs_to :produto
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :fornecedor
  belongs_to :card
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  alias_attribute :name, :descricao
  belongs_to :category
  belongs_to :unit
  has_many :movimentos
end

app/models/rodizio.rb
class Rodizio < ActiveRecord::Base
  belongs_to :card
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/tipodoc.rb
class Tipodoc < ActiveRecord::Base
end

app/models/unidade.rb
class Unidade < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :produtos
end

app/models/vale.rb
class Vale < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/vddessert.rb
class Vddessert < ActiveRecord::Base
  belongs_to :dessert
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: [:show, :edit, :update, :destroy]

  # GET /unidades
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades
  def create
    @unidade = Unidade.new(unidade_params)

    if @unidade.save
      redirect_to @unidade, notice: 'Unidade was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /unidades/1
  def update
    if @unidade.update(unidade_params)
      redirect_to @unidade, notice: 'Unidade was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /unidades/1
  def destroy
    @unidade.destroy
    redirect_to unidades_url, notice: 'Unidade was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def unidade_params
      params.require(:unidade).permit(:descricao)
    end
end

app/views/unidades/_form.html.slim
= simple_form_for(@unidade) do |f|
  = f.error_notification

  .form-inputs
    = f.input :descricao

  .form-actions
    = f.button :submit

app/views/unidades/edit.html.slim
h1 Unidade

== render 'form'

= link_to 'Ver', @unidade, class: 'btn btn-info btn-sm'
'|
= link_to 'Voltar', unidades_path, class: 'btn btn-info btn-sm'

app/views/unidades/index.html.slim
h1 Unidades

table
  tr
    th Descricao
    th


  - @unidades.each do |unidade|
    tr
      td = unidade.descricao
      td
        btn-group.pull-right
          = link_to 'Show', unidade, class: 'btn btn-info btn-sm'
          = link_to 'Edit', edit_unidade_path(unidade), class: 'btn btn-info btn-sm'
          = link_to 'Destroy', unidade, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-info btn-sm'

br

= link_to 'New Unidade', new_unidade_path, class: 'btn btn-info btn-sm'

app/views/unidades/new.html.slim
h1 Nova Unidade

== render 'form'

= link_to 'Voltar', unidades_path, class: 'btn btn-info btn-sm'

app/views/unidades/show.html.slim
p#notice = notice

p
  strong Descricao:
  = @unidade.descricao

= link_to 'Editar', edit_unidade_path(@unidade), class: 'btn btn-info btn-sm'
'|
= link_to 'Voltar', unidades_path, class: 'btn btn-info btn-sm'