config/routes.rb
Cbtg::Application.routes.draw do

  resources :tipodocs

  resources :formapgtos

  resources :cxdiarios

  resources :cofres

  resources :vddesserts

  resources :ctrldesserts

  resources :desserts

  resources :cards

  resources :rodizios

  resources :units

  resources :unidades

  resources :pagamentos

  resources :movimentos

  resources :falta

  root :to => redirect("/funcionarios")

  resources :categories

  resources :ocorrencia

  resources :cargos

  resources :funcionarios

  resources :vales

  resources :fornecedors

  resources :produtos

  resources :agendas

  resources :comandos

  resources :sites

  resources :rts

  resources :ctgs

  resources :mtgs

  resources :socios

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :rodizios
end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/category.rb
 class Category < ActiveRecord::Base
  alias_attribute :name, :descricao
  has_many :produtos
end

app/models/cofre.rb
class Cofre < ActiveRecord::Base
end

app/models/comando.rb
class Comando < ActiveRecord::Base
end

app/models/cxdiario.rb
class Cxdiario < ActiveRecord::Base
end

app/models/dessert.rb
class Dessert < ActiveRecord::Base
  has_many :ctrldesserts
end

app/models/faltum.rb
class Faltum < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/formapgto.rb
class Formapgto < ActiveRecord::Base
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  alias_attribute :name, :nome
  has_many :pagamentos
end

app/models/movimento.rb
class Movimento < ActiveRecord::Base
  belongs_to :produto
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :fornecedor
  belongs_to :card
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  alias_attribute :name, :descricao
  belongs_to :category
  belongs_to :unit
  has_many :movimentos
end

app/models/rodizio.rb
class Rodizio < ActiveRecord::Base
  belongs_to :card
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/tipodoc.rb
class Tipodoc < ActiveRecord::Base
end

app/models/unidade.rb
class Unidade < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :produtos
end

app/models/vale.rb
class Vale < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/vddessert.rb
class Vddessert < ActiveRecord::Base
  belongs_to :dessert
end

app/controllers/cofres_controller.rb
class CofresController < ApplicationController
  before_action :set_cofre, only: [:show, :edit, :update, :destroy]

  # GET /cofres
  def index
    @cofres = Cofre.all
  end

  # GET /cofres/1
  def show
  end

  # GET /cofres/new
  def new
    @cofre = Cofre.new
  end

  # GET /cofres/1/edit
  def edit
  end

  # POST /cofres
  def create
    @cofre = Cofre.new(cofre_params)

    if @cofre.save
      redirect_to @cofre, notice: 'Cofre was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /cofres/1
  def update
    if @cofre.update(cofre_params)
      redirect_to @cofre, notice: 'Cofre was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /cofres/1
  def destroy
    @cofre.destroy
    redirect_to cofres_url, notice: 'Cofre was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cofre
      @cofre = Cofre.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cofre_params
      params.require(:cofre).permit(:data, :dineiro, :moeda, :chqvista, :dolares, :euros)
    end
end

app/views/cofres/_form.html.slim
= simple_form_for(@cofre) do |f|
  = f.error_notification

  .form-inputs
    = f.input :data, label: 'Data'
    = f.input :dineiro, label: 'Dinheiro'
    = f.input :moeda, label: 'Moeda'
    = f.input :chqvista, label: 'Cheque a vista'
    = f.input :dolares, label: 'Dólares'
    = f.input :euros, label: 'Euros'

  .form-actions
    = f.button :submit

app/views/cofres/edit.html.slim
h1 Cofre

== render 'form'

= link_to 'Ver', @cofre, class: 'btn btn-info btn-sm'
'|
= link_to 'Voltar', cofres_path, class: 'btn btn-info btn-sm'

app/views/cofres/index.html.slim
h1 Listando Cofre

table.table.table-striped
  tr
    th Data
    th Dinheiro
    th Moeda
    th Cheques
    th Total em R$
    th Dolares
    th Euros
    th


  - @cofres.each do |cofre|
    tr
      td = cofre.data.strftime("%d-%m-%Y")
      td = valor_formatado(cofre.dineiro)
      td = valor_formatado(cofre.moeda)
      td = valor_formatado(cofre.chqvista)
      th = valor_formatado(cofre.dineiro + cofre.moeda + cofre.chqvista)
      td = valor_formatado(cofre.dolares)
      td = valor_formatado(cofre.euros)
      td
        .btn-group.pull-right
          = link_to 'Show', cofre, class: 'btn btn-info btn-sm'
          = link_to 'Edit', edit_cofre_path(cofre), class: 'btn btn-info btn-sm'
          = link_to 'Destroy', cofre, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-info btn-sm'

br

= link_to 'Novo cofre', new_cofre_path, class: 'btn btn-info btn-sm'

app/views/cofres/new.html.slim
h1 New cofre

== render 'form'

= link_to 'Voltar', cofres_path, class: 'btn btn-info btn-sm'

app/views/cofres/show.html.slim
p#notice = notice

p
  strong Data:
  = @cofre.data
p
  strong Dineiro:
  = @cofre.dineiro
p
  strong Moeda:
  = @cofre.moeda
p
  strong Chqvista:
  = @cofre.chqvista
p
  strong Dolares:
  = @cofre.dolares
p
  strong Euros:
  = @cofre.euros

= link_to 'Editar', edit_cofre_path(@cofre), class: 'btn btn-info btn-sm'
'|
= link_to 'Voltar', cofres_path, class: 'btn btn-info btn-sm'