config/routes.rb
Cbtg::Application.routes.draw do

  resources :tipodocs

  resources :formapgtos

  resources :cxdiarios

  resources :cofres

  resources :vddesserts

  resources :ctrldesserts

  resources :desserts

  resources :cards

  resources :rodizios

  resources :units

  resources :unidades

  resources :pagamentos

  resources :movimentos

  resources :falta

  root :to => redirect("/funcionarios")

  resources :categories

  resources :ocorrencia

  resources :cargos

  resources :funcionarios

  resources :vales

  resources :fornecedors

  resources :produtos

  resources :agendas

  resources :comandos

  resources :sites

  resources :rts

  resources :ctgs

  resources :mtgs

  resources :socios

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :rodizios
end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/category.rb
 class Category < ActiveRecord::Base
  alias_attribute :name, :descricao
  has_many :produtos
end

app/models/cofre.rb
class Cofre < ActiveRecord::Base
end

app/models/comando.rb
class Comando < ActiveRecord::Base
end

app/models/ctrldessert.rb
class Ctrldessert < ActiveRecord::Base
end

app/models/cxdiario.rb
class Cxdiario < ActiveRecord::Base
end

app/models/dessert.rb
class Dessert < ActiveRecord::Base
  has_many :ctrldesserts
end

app/models/faltum.rb
class Faltum < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/formapgto.rb
class Formapgto < ActiveRecord::Base
end

app/models/movimento.rb
class Movimento < ActiveRecord::Base
  belongs_to :produto
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :fornecedor
  belongs_to :card
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  alias_attribute :name, :descricao
  belongs_to :category
  belongs_to :unit
  has_many :movimentos
end

app/models/rodizio.rb
class Rodizio < ActiveRecord::Base
  belongs_to :card
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/tipodoc.rb
class Tipodoc < ActiveRecord::Base
end

app/models/unidade.rb
class Unidade < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :produtos
end

app/models/vale.rb
class Vale < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/vddessert.rb
class Vddessert < ActiveRecord::Base
  belongs_to :dessert
end

app/controllers/ctrldesserts_controller.rb
class CtrldessertsController < ApplicationController
  before_action :set_ctrldessert, only: [:show, :edit, :update, :destroy]

  # GET /ctrldesserts
  def index
    @ctrldesserts = Ctrldessert.all
  end

  # GET /ctrldesserts/1
  def show
  end

  # GET /ctrldesserts/new
  def new
    @ctrldessert = Ctrldessert.new
  end

  # GET /ctrldesserts/1/edit
  def edit
  end

  # POST /ctrldesserts
  def create
    @ctrldessert = Ctrldessert.new(ctrldessert_params)

    if @ctrldessert.save
      redirect_to @ctrldessert, notice: 'Ctrldessert was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /ctrldesserts/1
  def update
    if @ctrldessert.update(ctrldessert_params)
      redirect_to @ctrldessert, notice: 'Ctrldessert was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /ctrldesserts/1
  def destroy
    @ctrldessert.destroy
    redirect_to ctrldesserts_url, notice: 'Ctrldessert was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ctrldessert
      @ctrldessert = Ctrldessert.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ctrldessert_params
      params.require(:ctrldessert).permit(:data, :dessert_id, :almoco, :qtd)
    end
end

app/views/ctrldesserts/_form.html.slim
= simple_form_for(@ctrldessert) do |f|
  = f.error_notification

  .form-inputs
    = f.input :data
    = f.input :dessert_id
    = f.input :almoco
    = f.input :qtd

  .form-actions
    = f.button :submit

app/views/ctrldesserts/edit.html.slim
h1 Sobremesas

== render 'form'

= link_to 'Ver', @ctrldessert
'|
= link_to 'Voltar', ctrldesserts_path

app/views/ctrldesserts/index.html.slim
h1 Listing ctrldesserts

table
  tr
    th Data
    th Sobremesa
    th Almoço / Jantar
    th Qtd
    th


  - @ctrldesserts.each do |ctrldessert|
    tr
      td = ctrldessert.data
      td = ctrldessert.dessert_id
      td = ctrldessert.almoco
      td = ctrldessert.qtd
      td
        .btn-group.pull-right
          = link_to 'Show', ctrldessert, class: 'btn btn-info btn-sm'
          = link_to 'Edit', edit_ctrldessert_path(ctrldessert), class: 'btn btn-info btn-sm'
          = link_to 'Destroy', ctrldessert, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-info btn-sm'

br

= link_to 'Nova Sobremesa', new_ctrldessert_path, class: 'btn btn-info btn-sm'

app/views/ctrldesserts/new.html.slim
h1 Nova sobremesa

== render 'form'

= link_to 'Voltar', ctrldesserts_path, class: 'btn btn-info btn-sm'

app/views/ctrldesserts/show.html.slim
p#notice = notice

p
  strong Data:
  = @ctrldessert.data
p
  strong Dessert:
  = @ctrldessert.dessert_id
p
  strong Almoco:
  = @ctrldessert.almoco
p
  strong Qtd:
  = @ctrldessert.qtd

= link_to 'Editar', edit_ctrldessert_path(@ctrldessert), class: 'btn btn-info btn-sm'
'|
= link_to 'Voltar', ctrldesserts_path, class: 'btn btn-info btn-sm'