config/routes.rb
Cbtg::Application.routes.draw do

  resources :tipodocs

  resources :formapgtos

  resources :cxdiarios

  resources :cofres

  resources :vddesserts

  resources :ctrldesserts

  resources :desserts

  resources :cards

  resources :rodizios

  resources :units

  resources :unidades

  resources :pagamentos

  resources :movimentos

  resources :falta

  root :to => redirect("/funcionarios")

  resources :categories

  resources :ocorrencia

  resources :cargos

  resources :funcionarios

  resources :vales

  resources :fornecedors

  resources :produtos

  resources :agendas

  resources :comandos

  resources :sites

  resources :rts

  resources :ctgs

  resources :mtgs

  resources :socios

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :rodizios
end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/category.rb
 class Category < ActiveRecord::Base
  alias_attribute :name, :descricao
  has_many :produtos
end

app/models/cofre.rb
class Cofre < ActiveRecord::Base
end

app/models/comando.rb
class Comando < ActiveRecord::Base
end

app/models/cxdiario.rb
class Cxdiario < ActiveRecord::Base
end

app/models/dessert.rb
class Dessert < ActiveRecord::Base
  has_many :ctrldesserts
end

app/models/faltum.rb
class Faltum < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/formapgto.rb
class Formapgto < ActiveRecord::Base
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  alias_attribute :name, :nome
  has_many :pagamentos
end

app/models/movimento.rb
class Movimento < ActiveRecord::Base
  belongs_to :produto
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :fornecedor
  belongs_to :card
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  alias_attribute :name, :descricao
  belongs_to :category
  belongs_to :unit
  has_many :movimentos
end

app/models/rodizio.rb
class Rodizio < ActiveRecord::Base
  belongs_to :card
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/tipodoc.rb
class Tipodoc < ActiveRecord::Base
end

app/models/unidade.rb
class Unidade < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :produtos
end

app/models/vale.rb
class Vale < ActiveRecord::Base
  belongs_to :funcionario
end

app/models/vddessert.rb
class Vddessert < ActiveRecord::Base
  belongs_to :dessert
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  def index
    @units = Unit.all
  end

  # GET /units/1
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to @unit, notice: 'Unit was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /units/1
  def update
    if @unit.update(unit_params)
      redirect_to @unit, notice: 'Unit was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /units/1
  def destroy
    @unit.destroy
    redirect_to units_url, notice: 'Unit was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def unit_params
      params.require(:unit).permit(:name, :sigla)
    end
end

app/views/units/_form.html.slim
= simple_form_for(@unit) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :sigla

  .form-actions
    = f.button :submit

app/views/units/edit.html.slim
h1 Unidade

== render 'form'

= link_to 'Ver', @unit, class: 'btn btn-info btn-sm'
'|
= link_to 'Voltar', units_path, class: 'btn btn-info btn-sm'

app/views/units/index.html.slim
h1 Unidades

table.table.table-striped
  tr
    th Name
    th Sigla
    th


  - @units.each do |unit|
    tr
      td = unit.name
      td = unit.sigla
      td
        .btn-group.pull-right
          = link_to 'Ver', unit, class: 'btn btn-info btn-sm'
          = link_to 'Editar', edit_unit_path(unit), class: 'btn btn-info btn-sm'
          = link_to 'Deletar', unit, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-info btn-sm'

br

= link_to 'Nova Unidade', new_unit_path, class: 'btn btn-info btn-sm'

app/views/units/new.html.slim
h1 Nova Unidade

== render 'form'

= link_to 'Voltar', units_path, class: 'btn btn-info btn-sm'

app/views/units/show.html.slim
p#notice = notice

p
  strong Name:
  = @unit.name
p
  strong Sigla:
  = @unit.sigla

= link_to 'Editar', edit_unit_path(@unit), class: 'btn btn-info btn-sm'
'|
= link_to 'Voltar', units_path, class: 'btn btn-info btn-sm'